import { useEffect, useMemo, useState } from "react";
import { motion as Motion } from "framer-motion";
import {
  Activity,
  Cloud,
  Download,
  ExternalLink,
  FileText,
  Loader2,
  ShieldAlert,
} from "lucide-react";
import { api, ApiError } from "../lib/api";

const TYPE_META = {
  threat_model: {
    label: "Threat model",
    icon: ShieldAlert,
    accent: "text-violet-500 bg-violet-500/10",
  },
  cloud_compliance: {
    label: "Cloud compliance",
    icon: Cloud,
    accent: "text-sky-500 bg-sky-500/10",
  },
  endpoint_security: {
    label: "Endpoint security",
    icon: Activity,
    accent: "text-emerald-500 bg-emerald-500/10",
  },
};

const FILTERS = [
  { id: "all", label: "All" },
  { id: "threat_model", label: "Threat models" },
  { id: "cloud_compliance", label: "Cloud compliance" },
  { id: "endpoint_security", label: "Endpoint security" },
];

const formatBytes = (n) => {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
};

const formatWhen = (iso) => {
  const d = new Date(iso);
  return d.toLocaleString([], {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
};

// Same-origin via the Vite proxy so the session cookie rides along on direct
// navigations (View/Download). VITE_API_BASE overrides for prod builds where
// the backend is on a different host.
const reportUrl = (id, { download = false } = {}) => {
  const base = import.meta.env.VITE_API_BASE ?? "";
  return `${base}/reports/${encodeURIComponent(id)}${download ? "?download=1" : ""}`;
};

export default function Reports() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const data = await api.get("/reports");
        if (!cancelled) {
          setItems(data);
          setLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError(
            err instanceof ApiError
              ? err.body?.error || err.message
              : err?.message || "Failed to load reports"
          );
          setLoading(false);
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const filtered = useMemo(
    () => (filter === "all" ? items : items.filter((r) => r.type === filter)),
    [items, filter]
  );

  const counts = useMemo(() => {
    const by = { all: items.length };
    for (const r of items) by[r.type] = (by[r.type] || 0) + 1;
    return by;
  }, [items]);

  return (
    <div className="px-8 py-12 max-w-5xl w-full mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-semibold text-[var(--text-h)] tracking-tight mb-2">
          Reports
        </h1>
        <p className="text-[var(--text-muted)]">
          Threat model and cloud compliance reports generated by the agents.
          Click to view in a new tab, or download to share.
        </p>
      </div>

      <div className="flex items-center gap-2 mb-6">
        {FILTERS.map((f) => {
          const active = filter === f.id;
          const n = counts[f.id] || 0;
          return (
            <button
              key={f.id}
              type="button"
              onClick={() => setFilter(f.id)}
              className={[
                "inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-[13px] font-medium transition-colors",
                active
                  ? "bg-[var(--accent-bg)] text-[var(--accent)]"
                  : "text-[var(--text-muted)] hover:text-[var(--text-h)] hover:bg-[var(--bg-subtle)]",
              ].join(" ")}
            >
              {f.label}
              <span
                className={[
                  "text-[11px] px-1.5 py-0.5 rounded-md",
                  active ? "bg-[var(--accent)] text-white" : "bg-[var(--bg-subtle)]",
                ].join(" ")}
              >
                {n}
              </span>
            </button>
          );
        })}
      </div>

      {error && (
        <div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-3 text-[13px] text-red-500">
          {error}
        </div>
      )}

      {loading ? (
        <div className="rounded-2xl border border-[var(--border-soft)] bg-[var(--bg-elev)] p-10 text-center text-[var(--text-muted)]">
          <Loader2 size={20} className="animate-spin mx-auto mb-2" />
          Loading reports…
        </div>
      ) : filtered.length === 0 ? (
        <div className="rounded-2xl border border-[var(--border-soft)] bg-[var(--bg-elev)] p-10 text-center text-[var(--text-muted)]">
          No reports yet. Run a threat model or cloud compliance scan from chat
          and the report will show up here.
        </div>
      ) : (
        <div className="grid gap-2">
          {filtered.map((r) => {
            const meta = TYPE_META[r.type] || {
              label: r.type,
              icon: FileText,
              accent: "text-[var(--text-muted)] bg-[var(--bg-subtle)]",
            };
            const Icon = meta.icon;
            return (
              <Motion.div
                key={r.id}
                layout
                initial={{ opacity: 0, y: 4 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex items-start gap-3 px-4 py-3 rounded-xl border border-[var(--border-soft)] bg-[var(--bg-elev)] hover:border-[var(--accent-ring)] transition-all"
              >
                <div className={["size-9 rounded-lg grid place-items-center shrink-0 mt-0.5", meta.accent].join(" ")}>
                  <Icon size={16} strokeWidth={1.75} />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-[14px] font-medium text-[var(--text-h)] truncate">
                      {r.title}
                    </span>
                    <span className={["text-[11px] px-1.5 py-0.5 rounded-md font-medium", meta.accent].join(" ")}>
                      {meta.label}
                    </span>
                  </div>
                  <div className="mt-0.5 text-[12px] text-[var(--text-muted)] truncate font-mono">
                    {r.id}
                  </div>
                  <div className="mt-0.5 text-[12px] text-[var(--text-muted)]">
                    {formatBytes(r.size)} · {formatWhen(r.modified_at)}
                  </div>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <a
                    href={reportUrl(r.id)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[13px] text-[var(--text-h)] hover:bg-[var(--bg-subtle)] transition-colors"
                  >
                    <ExternalLink size={14} /> View
                  </a>
                  <a
                    href={reportUrl(r.id, { download: true })}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[13px] bg-[var(--accent)] hover:bg-[var(--accent-h)] text-white transition-colors"
                  >
                    <Download size={14} /> Download
                  </a>
                </div>
              </Motion.div>
            );
          })}
        </div>
      )}
    </div>
  );
}
